spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demodb
    username: root
    password: 123456

logging:
  config: classpath:log4j2.yml

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml